#ifndef PICASSO_TEST_SERIAL_CATEGORY_HPP
#define PICASSO_TEST_SERIAL_CATEGORY_HPP

#define TEST_CATEGORY serial
#define TEST_EXECSPACE Kokkos::Serial
#define TEST_MEMSPACE Kokkos::HostSpace
#define TEST_DEVICE Kokkos::Device<TEST_EXECSPACE,TEST_MEMSPACE>

#endif // end PICASSO_TEST_SERIAL_CATEGORY_HPP
