#ifndef HARLOW_TEST_OPENMP_CATEGORY_HPP
#define HARLOW_TEST_OPENMP_CATEGORY_HPP

#define TEST_CATEGORY openmp
#define TEST_EXECSPACE Kokkos::OpenMP
#define TEST_MEMSPACE Kokkos::HostSpace
#define TEST_DEVICE Kokkos::Device<TEST_EXECSPACE,TEST_MEMSPACE>

#endif // end HARLOW_TEST_OPENMP_CATEGORY_HPP
