#ifndef HARLOW_TEST_SERIAL_CATEGORY_HPP
#define HARLOW_TEST_SERIAL_CATEGORY_HPP

#define TEST_CATEGORY serial
#define TEST_EXECSPACE Kokkos::Serial
#define TEST_MEMSPACE Kokkos::HostSpace

#endif // end HARLOW_TEST_SERIAL_CATEGORY_HPP
